---
- hosts: all
  become: true
  gather_facts: no
  ignore_unreachable: true

  tasks:
  - name: Setup speed test server
    tags: speedtest
    import_role:
      name: speedtest_server

#- hosts: jsstreaming
#  become: true
#    - name: Setup Jellyfin
#      tags: jellyfin
#      import_role:
#        name: jellyfin_server

#- hosts: jsdns
#  become: true
#    - name: Setup Pi-Hole
#      tags: dns
#      import_role:
#        name: pihole_server

#- hosts: jsgit
#  become: true
#    - name: Setup Gitea
#      tags: git
#      import_role:
#        name: git_server

#- hosts: jsunifi
#  become: true
#    - name: Setup Unifi Controller
#      tags: unifi
#      import_role:
#        name: unifi
